default_install_hook_types:
  - pre-commit
default_stages:
  - pre-commit

repos:
  - repo: local
    hooks:
      - id: trim-trailing-whitespace
        name: trim trailing whitespace
        entry: python scripts/precommit_local.py trim-trailing-whitespace
        language: system
        types: [text]
      - id: fix-end-of-file
        name: fix end of file
        entry: python scripts/precommit_local.py fix-end-of-file
        language: system
        types: [text]
      - id: check-merge-conflict
        name: check merge conflict
        entry: python scripts/precommit_local.py check-merge-conflict
        language: system
        types: [text]
      - id: check-yaml
        name: check yaml
        entry: python scripts/precommit_local.py check-yaml
        language: system
        files: \.(yml|yaml)$
      - id: check-toml
        name: check toml
        entry: python scripts/precommit_local.py check-toml
        language: system
        files: \.toml$
      - id: ruff
        name: ruff
        entry: python scripts/precommit_local.py ruff-fix
        language: system
        types_or: [python, pyi]
      - id: black
        name: black
        entry: python scripts/precommit_local.py black
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: python scripts/precommit_local.py mypy
        language: system
        pass_filenames: false
